author: Checkout
author_url: https://www.checkout.com/
github_url: https://github.com/checkout/checkout-sdk-ios
output: docs
theme: fullwidth
documentation: Documentation/**/*.md
exclude:
  - Source/PhoneNumberKit/*.swift
custom_categories:
  - name: Guides
    children:
      - Usage
      - Demo
      - Customizing the Card View
  - name: Walkthrough
    children:
      - iOS Example Frames
clean: true